[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "benchmarks"
authors = [{name = "UM-Bridge Team", email = ""}]
dynamic = ["version", "description"]
