name: benchmark-achlys

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: benchmarks/achlys/
          push: true
          tags: linusseelinger/benchmark-achlys:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      model:
        image: linusseelinger/benchmark-achlys:latest
        ports:
        - 4243:4243

    steps:
       -
        name: Validate
        run: |
          docker run --network=host -e input_value="[0.8, 1.0, 1.3, 9e-4, 9e-4]" -e model_host=http://localhost:4243 linusseelinger/testing-protocol-conformity-current:latest
