name: benchmark-analytic-banana

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: benchmarks/analytic-banana/
          push: true
          tags: linusseelinger/benchmark-analytic-banana:latest

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    needs: build

    services:
      model:
        image: linusseelinger/benchmark-analytic-banana:latest
        ports:
        - 4243:4243

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Dependencies
        run: |
          apt update; apt install -y python3-pip; pip3 install pytest requests jsonschema
       -
        name: Validate
        run: |
          pytest -v test/test_model_schema.py --model_url http://model:4243
