name: generate-documentation

on:
  push:
    branches:
      - 'docs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2

      -
        name: Generate rst files from readmes
        working-directory: docs
        run: |
            bash generate_rst_files_from_readmes.sh

      -
        name: push changes to remote without triggering CI
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add --force ./docs/source/benchmarks/* ./docs/source/models/*
          git commit -m "[skip ci] Generate rst files" || echo "Nothing to push"
          git push
