name: achlys

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build achlys-ubuntu
        uses: docker/build-push-action@v3
        with:
          context: https://raw.githubusercontent.com/aurora-multiphysics/achlys/master/docker/achlys-ubuntu/moose-stable/Dockerfile
          push: true
          build-args: |
            compile_cores=4
            build_git_sha=master 
          tags: achlys-ubuntu
      - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: models/achlys
          push: true
          tags: linusseelinger/model-achlys:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      model:
        image: linusseelinger/model-achlys:latest
        ports:
        - 4242:4242

    steps:
       -
        name: Validate protocol
        run: |
          docker run --network=host -e model_host=http://localhost:4242 linusseelinger/testing-protocol-conformity-current:latest
